excluded: # paths to ignore during linting. overridden by `included`.
  - R.generated.swift
  - Pods
  - CurrencyExchangeRateApp/Resources
# parameterized rules can be customized from this configuration file
file_length:
  - 700
  - 1000
line_length:
  - 230
  - 250
# parameterized rules are first parameterized as a warning level, then error level.
function_body_length:
  - 150 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
disabled_rules:
  - trailing_whitespace
  - type_name
  - identifier_name
  - line_length
  - superfluous_disable_command
