# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyExchangeRateApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint', '0.40.3'
  pod 'ReachabilitySwift', '5.0.0'

  target 'CurrencyExchangeRateAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyExchangeRateAppUITests' do
    # Pods for testing
  end

end
